# Uncomment the next line to define a global platform for your project
platform :ios, '14.5'

target 'ChatApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChatApp
	pod 'Firebase/Core'
	pod 'Firebase/Auth'
	pod 'Firebase/Storage'
	pod 'Firebase/Firestore'
	pod 'SDWebImage', '~> 5.0'
	pod 'JGProgressHUD'

end
